ALTER TABLE IF EXISTS position DROP CONSTRAINT IF EXISTS position_item_id_fkey;
DROP TABLE IF EXISTS item;
DROP TABLE IF EXISTS position;

CREATE TABLE item(
id SERIAL PRIMARY KEY,
name VARCHAR(255),
price integer);

CREATE TABLE position(
id SERIAL PRIMARY KEY,
item_id INTEGER REFERENCES item(id) ON DELETE RESTRICT ON UPDATE CASCADE,
amount INTEGER,
UNIQUE(item_id));